language: node_js
sudo: false
node_js:
  - "5.5"
env:
  - PATH=$HOME/purescript:$PATH
install:
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.11.2/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install -g bower pulp@^11.0.0
  - bower install
script:
  - travis_wait pulp build
  - travis_wait make run-example
  - travis_wait pulp test

cache:
  directories:
    - output
